M48
; DRILL file {KiCad (6.0.0)} date Mon Sep 19 18:58:27 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-09-19T18:58:27+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
%
G90
G05
T1
X207.475Y-49.63
X212.325Y-49.63
T2
X207.175Y-46.6
X212.625Y-46.6
T0
M30
